### ISSUE TITLE
Make sure we expose this on the doc site

### ISSUE THREAD

**Issue by mcdonnelldean** [senecajs/getting-started#1]
@geek We need to look at giving this repo some attention I think and getting it linked up in the doc site.

[Trello Card](https://trello.com/c/WNo9TP18/74-getting-started-make-sure-we-expose-this-on-the-doc-site)

**Comment by AdrieanKhisbe** [comment]
card is broken, but will be done before the week end :)

**Comment by AdrieanKhisbe** [comment]
:)

**Comment by AdrieanKhisbe** [comment]
Done in https://github.com/senecajs/senecajs.org/commit/549dca85b0e85c3e7fa5381036fd6f44e0ca8366
